<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SprocketMod.props" />
  <PropertyGroup>
    <AssemblyName>SprocketQoL</AssemblyName>
    <Version>1.8.6</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
